apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: nginx-ingress-controller
  namespace: kube-system
spec:
  rules:
    - host: nginx-ingress.huisebug.com
      http:
        paths:
          - backend:
              serviceName: nginx-ingress-controller
              servicePort: 80
            path: /
